export interface WalletInfo {
  name: string;
}

export const walletConfig: { [walletAddress: string]: WalletInfo } = {
  { "wallet_address": "HKjuMsz7JMuiQhkZsAwqogPf1KwhwACZGMcTmmtesoWv", "name": "Jerry" },
  { "wallet_address": "DYAn4XpAkN5mhiXkRB7dGq4Jadnx6XYgu8L5b3WGhbrt", "name": "The Doc" },
  { "wallet_address": "7ABz8qEFZTHPkovMDsmQkm64DZWN5wRtU7LEtD2ShkQ6", "name": "Red" },
  { "wallet_address": "CqQKv6XdrMWrz3YuSwqTTcVoQK5eu4zNo3hps3M1Q3yo", "name": "Jaden" },
  { "wallet_address": "7mWRFwxDke8KvEcdN2ZkviTTsupch8rccf5YWpBWj15t", "name": "Geni" },
  { "wallet_address": "5t9xBNuDdGTGpjaPTx6hKd7sdRJbvtKS8Mhq6qVbo8Qz", "name": "Smokez" },
  { "wallet_address": "m7Kaas3Kd8FHLnCioSjCoSuVDReZ6FDNBVM6HTNYuF7", "name": "Ferb" },
  { "wallet_address": "FRbUNvGxYNC1eFngpn7AD3f14aKKTJVC6zSMtvj2dyCS", "name": "Henn100x" },
  { "wallet_address": "4WPTQA7BB4iRdrPhgNpJihGcxKh8T43gLjMn5PbEVfQw", "name": "Oura" },
  { "wallet_address": "3pZ59YENxDAcjaKa3sahZJBcgER4rGYi4v6BpPurmsGj", "name": "Kadenox" },
  { "wallet_address": "G3g1CKqKWSVEVURZDNMazDBv7YAhMNTjhJBVRTiKZygk", "name": "Insyder" },
  { "wallet_address": "2kv8X2a9bxnBM8NKLc6BBTX2z13GFNRL4oRotMUJRva9", "name": "Gh0stee" },
  { "wallet_address": "HmBmSYwYEgEZuBUYuDs9xofyqBAkw4ywugB1d7R7sTGh", "name": "Tobx" },
  { "wallet_address": "4BdKaxN8G6ka4GYtQQWk4G4dZRUTX2vQH9GcXdBREFUk", "name": "Jijo" },
  { "wallet_address": "7VBTpiiEjkwRbRGHJFUz6o5fWuhPFtAmy8JGhNqwHNnn", "name": "Brox" },
  { "wallet_address": "525LueqAyZJueCoiisfWy6nyh4MTvmF4X9jSqi6efXJT", "name": "Joji" },
  { "wallet_address": "AJ6MGExeK7FXmeKkKPmALjcdXVStXYokYNv9uVfDRtvo", "name": "Tim" },
  { "wallet_address": "Aen6LKc7sGVPTyjMd5cu9B9XVjL7m9pnvAiP2ZNJC4GZ", "name": "Aroa" },
  { "wallet_address": "41uh7g1DxYaYXdtjBiYCHcgBniV9Wx57b7HU7RXmx1Gg", "name": "Lowskii" },
  { "wallet_address": "ATKi3ZvMbo31pbgBgGSGQPDPKEbQ4oGzoDrwG2sms56k", "name": "Nach" },
  { "wallet_address": "9FNz4MjPUmnJqTf6yEDbL1D4SsHVh7uA8zRHhR5K138r", "name": "Danny" },
  { "wallet_address": "8rvAsDKeAcEjEkiZMug9k8v1y8mW6gQQiMobd89Uy7qR", "name": "Casino" },
  { "wallet_address": "6m5sW6EAPAHncxnzapi1ZVJNRb9RZHQ3Bj7FD84X9rAF", "name": "ShockedJS" },
  { "wallet_address": "2CXbN6nuTTb4vCrtYM89SfQHMMKGPAW4mvFe6Ht4Yo6z", "name": "MoneyMaykah" },
  { "wallet_address": "9ecRdqNCBxwReiY2pxtnLeayeBzE1CrSSmKKJJGdmsaJ", "name": "lowkey" },
  { "wallet_address": "7tiRXPM4wwBMRMYzmywRAE6jveS3gDbNyxgRrEoU6RLA", "name": "Qtdegen" },
  { "wallet_address": "DsqRyTUh1R37asYcVf1KdX4CNnz5DKEFmnXvgT4NfTPE", "name": "Classic" },
  { "wallet_address": "GwoFJFjUTUSWq2EwTz4P2Sznoq9XYLrf8t4q5kbTgZ1R", "name": "Levis" },
  { "wallet_address": "6LChaYRYtEYjLEHhzo4HdEmgNwu2aia8CM8VhR9wn6n7", "name": "Assasin.eth" },
  { "wallet_address": "EAnB5151L8ejp3SM6haLgyv3snk6oqc8acKgWEg9T5J", "name": "Jordan" },
  { "wallet_address": "8MaVa9kdt3NW4Q5HyNAm1X5LbR8PQRVDc1W8NMVK88D5", "name": "Daumen" },
  { "wallet_address": "DNfuF1L62WWyW3pNakVkyGGFzVVhj4Yr52jSmdTyeBHm", "name": "Gake" },
  { "wallet_address": "5B52w1ZW9tuwUduueP5J7HXz5AcGfruGoX6YoAudvyxG", "name": "Yenni" },
  { "wallet_address": "BCagckXeMChUKrHEd6fKFA1uiWDtcmCXMsqaheLiUPJd", "name": "dv" },
  { "wallet_address": "J2B5fnm2DAAUAGa4EaegwQFoYaN6B5FerGA5sjtQoaGM", "name": "Dan176" },
  { "wallet_address": "86AEJExyjeNNgcp7GrAvCXTDicf5aGWgoERbXFiG1EdD", "name": "Publix" },
  { "wallet_address": "3FDci33mzMKNdNxzSS9D13XyNZQAdfmpvtDZLWPbZiAU", "name": "Sachs" },
  { "wallet_address": "As7HjL7dzzvbRbaD3WCun47robib2kmAKRXMvjHkSMB5", "name": "Otta" },
  { "wallet_address": "5wcc13mXoyqe6qh2iHH5GFknojoJ7y13ZPx9K4NXTuo3", "name": "Dolo" },
  { "wallet_address": "HUS9ErdrDqpqQePbmfgJUTnDTE6eZ8ES62a25RihSK9U", "name": "Hustler" },
  { "wallet_address": "831yhv67QpKqLBJjbmw2xoDUeeFHGUx8RnuRj9imeoEs", "name": "Trey" },
  { "wallet_address": "GM7Hrz2bDq33ezMtL6KGidSWZXMWgZ6qBuugkb5H8NvN", "name": "Beaver" },
  { "wallet_address": "mW4PZB45isHmnjGkLpJvjKBzVS5NXzTJ8UDyug4gTsM", "name": "Dex" },
  { "wallet_address": "Gv7CnRo2L2SJ583XEfoKHKbmWK3wNoBDxVoJqMKJR4Nu", "name": "Robo" },
  { "wallet_address": "8YYDiCbPd4nM8TxrQEVdPA4aG8jys8R7Z1kKsgPL4pwh", "name": "Michi" },
  { "wallet_address": "3nvC8cSrEBqFEXZjUpKfwZMPk7xYdqcnoxmFBjXiizVX", "name": "Value & Time" },
  { "wallet_address": "3mPypxb7ViYEdLv4siFmESvY5w5ZKknwgmB4TPcZ77qe", "name": "Carti The Menace" },
  { "wallet_address": "GJA1HEbxGnqBhBifH9uQauzXSB53to5rhDrzmKxhSU65", "name": "Latuche" },
  { "wallet_address": "42nsEk51owYM3uciuRvFerqK77yhXZyjBLRgkDzJPV2g", "name": "Izzy" },
  { "wallet_address": "AGnd5WTHMUbyK3kjjQPdQFM3TbWcuPTtkwBFWVUwiCLu", "name": "Angi" },
  { "wallet_address": "EHg5YkU2SZBTvuT87rUsvxArGp3HLeye1fXaSDfuMyaf", "name": "TIL" },
  { "wallet_address": "5AyJw1VNDgTho2chipbVmuGqTuX1fCvVkLneChQkQrw8", "name": "Bolivian" },
  { "wallet_address": "3h65MmPZksoKKyEpEjnWU2Yk2iYT5oZDNitGy5cTaxoE", "name": "Jidn" },
  { "wallet_address": "9yGxZ43ngT7LvwquVdUAYPvJzVyY65cS6mQvuJXjTEUc", "name": "Xelf" },
  { "wallet_address": "DfMxre4cKmvogbLrPigxmibVTTQDuzjdXojWzjCXXhzj", "name": "Euris" },
  { "wallet_address": "CyaE1VxvBrahnPWkqm5VsdCvyS2QmNht2UFrKJHga54o", "name": "Cented" },
  { "wallet_address": "Ds8mcuP5r2phg596mLui3ti3PJtVvFRw19Eo9UFdJ5Bc", "name": "Jazz" },
  { "wallet_address": "8zFZHuSRuDpuAR7J6FzwyF3vKNx4CVW3DFHJerQhc7Zd", "name": "Pow" },
  { "wallet_address": "2UfCfxdWrwnPDVvT245EwmcyUabQE2wuWYcBozj44ZA1", "name": "Lynk" },
  { "wallet_address": "FEYmfSL4B3Hhk5BzyEJNpHRiwAoMvzdNe2oa1UTKmbYT", "name": "Idontpaytaxes" },
  { "wallet_address": "DBmRHNbSsVX8F6NyVaaaiuGdwo1aYGawiy3jfNcvXYSC", "name": "Bobby" },
  { "wallet_address": "JDd3hy3gQn2V982mi1zqhNqUw1GfV2UL6g76STojCJPN", "name": "West" },
  { "wallet_address": "BTf4A2exGK9BCVDNzy65b9dUzXgMqB4weVkvTMFQsadd", "name": "Kev" },
  { "wallet_address": "BXNiM7pqt9Ld3b2Hc8iT3mA5bSwoe9CRrtkSUs15SLWN", "name": "Absol" },
  { "wallet_address": "5TuiERc4X7EgZTxNmj8PHgzUAfNHZRLYHKp4DuiWevXv", "name": "Rev" },
  { "wallet_address": "DpNVrtA3ERfKzX4F8Pi2CVykdJJjoNxyY5QgoytAwD26", "name": "Gorilla Capital" },
  { "wallet_address": "CSHktdVEmJybwNR9ft3sDfSc2UKgTPZZ8km26XfHYZDt", "name": "Lynk" },
  { "wallet_address": "99i9uVA7Q56bY22ajKKUfTZTgTeP5yCtVGsrG9J4pDYQ", "name": "Zrool" },
  { "wallet_address": "9yYya3F5EJoLnBNKW6z4bZvyQytMXzDcpU5D6yYr4jqL", "name": "Loopier" },
  { "wallet_address": "2YJbcB9G8wePrpVBcT31o8JEed6L3abgyCjt5qkJMymV", "name": "AI4N" }
  }

  
  
};
